/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutComponent: typeof import('./src/components/About-Component.vue')['default']
    BenefitsCarousel: typeof import('./src/components/miniComponents/Benefits-Carousel.vue')['default']
    ContactComponent: typeof import('./src/components/Contact-Component.vue')['default']
    FeesComponent: typeof import('./src/components/Fees-Component.vue')['default']
    FooterComponent: typeof import('./src/components/Footer-Component.vue')['default']
    HeroComponent: typeof import('./src/components/Hero-Component.vue')['default']
    HROutsourcingComponent: typeof import('./src/components/HROutsourcing-Component.vue')['default']
    NavbarComponent: typeof import('./src/components/Navbar-Component.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServicesComponent: typeof import('./src/components/Services-Component.vue')['default']
    TimelineComponent: typeof import('./src/components/Timeline-Component.vue')['default']
    UCarousel: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue')['default']
  }
}
